name: sar-autofocus
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - opencv
  - scikit-learn
  - scikit-image
  - pyyaml
  - jupyter
  - pip
  - pip:
      - tensorflow>=2.12
